---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-secret
spec:
  encryptedData:
    password: AgB3oeJ5BuxADGc0VOqgfvDZhbGL1sNfQP+k1DqKgpkLVDWIhq/VqlvXy9QDnYYVn6dyL4oUaQtzwoBu8bMGdcfO6G/RuEPXXDZb4Qf+ZagEOQWm/65dikmtEuEzGQtOUwkUzsqcbSDwyXoprqp1NPz8I9yRKdhCeUhGZwztAo2JJP/Wxj2Q0wQN6WXGHihAybOW169mGp5eER4Jk3tgXBNnWB62fkjgr9StghR5bn30Hmy34UwG7+MEou7UMQyZXx5SlLtnRl0VIFnAXs8fLsD0QnsgD44KeNOw6oPCcCnMXDeTug34w/u3TV8CakFtbyYHRwpx491O3TE1m26NqSlScn28Hi7xZ+cWs6liZjdlyjNLycMpfabqgpfrKZ/B2zImz4PeBaiJjftRLV0jENB6DTA2W2UiiL02cg7oz5uP/09WDWoI4uTAahwSwe8ie8As45hvFKcLkjd7cRxLCX9uUMe0X5L+kaC+gZ45r/zLTxKJ8GW32cuI0xPThoRgUZ2pfou3ocTKGW6LQ09kzObW/9+4jRje7wl7yoYgMO6zNp8HwveLnEL9BJ+PdwYB4zOFmfFtJAXjbZ/O7cXB+qbuDodd5P/hkuBweVsqr0sQqn6GuCs59cY1qKHQCeWR9lXxAZBIZSRf/YY3yppLcOHrOmngrJuGJxB85X7rmATVe5pC6/eGz9M5c+YAo3AuKJ7p2AMkgCA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-secret
