frontend:
  image: gebangfeng/frontend
  tag: d5b47a3
  autoscaling:
    averageUtilization: 90
backend:
  image: gebangfeng/backend
  tag: d5b47a3
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
